Repository codestates-seb/seb41_main_009, pull requests merged in 2023-02, with the labels that each got.

#225 [FE] Showcase/Comment 버그수정 및 기능추가
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/atoms/Category.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentHeader.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/organisms/Dropdown.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/organisms/showcase/Showcasebox.js
  client/src/components/pages/SearchPage.js
  client/src/components/pages/ShowcaseCreatePage.js
  client/src/components/pages/ShowcasePage.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useInputImage.js
  client/src/hooks/useIntersect.js
  client/src/store/showcaseCreateStore.js
  client/src/store/showcaseModalStore.js
  client/src/store/showcaseStore.js
Labels: feature, front

#227 [Be/member] 가입 로직 변경
  .gitignore
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginSuccessHandler.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
Labels: bug, back

#223 [FE] Login 이메일 인증 API 수정
  client/src/components/molecules/signup/EmailBox.js
  client/src/components/molecules/signup/EmailValidationBox.js
  client/src/hooks/useGetPost.js
Labels: feature, front

#230 [Be/post]Post 리팩토링
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostCommentRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
Labels: back

#233 [Be/post]Post 리팩토링
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostRepository.java
Labels: bug, back

#235 [Be/member] 가입 로직 변경
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
Labels: bug, back

#237 [Be/post]Post 조회 에러 해결
  server/src/main/java/com/codestates/hobby/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
Labels: bug

#232 README 생성
  README.md
Labels: documentation, back, front

#242 [FE] Post 페이지 수정
  client/src/components/atoms/Buttons.js
  client/src/components/molecules/SearchInput.js
  client/src/components/molecules/dropdown/DropdownSeriesList.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/list/SeriesCard.js
  client/src/components/molecules/posts/PostContentViewer.js
  client/src/components/molecules/posts/PostIndexLIstRender.js
  client/src/components/molecules/series/SeriesInfo.js
  client/src/components/molecules/series/SeriesPostList.js
  client/src/components/organisms/Lnb.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/organisms/listContainter/PostListContainer.js
  client/src/components/organisms/posts/PostContentLayer.js
  client/src/components/organisms/posts/PostHeaderLayer.js
  client/src/components/organisms/posts/PostSubHeaderLayer.js
  client/src/components/pages/PostInSeriesPage.js
  client/src/components/pages/PostListPage.js
  client/src/components/pages/PostPage.js
  client/src/components/pages/SearchPage.js
  client/src/components/pages/SeriesPage.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetPostList.js
  client/src/hooks/useGetSeries.js
  client/src/hooks/useGetSeriesListbyUser.js
  client/src/hooks/useGetSeriesPostList.js
Labels: front

#229 [FE] 컴포넌트 위치 수정 및 Post 생성 페이지 이미지 추가 로직 구현
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/atoms/TextEditor.js
  client/src/components/molecules/Pagination.js
  client/src/components/molecules/sidbar/SidebarMenu.js
  client/src/components/molecules/sidbar/SidebarTagsContainer.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/Signupbox.js
  client/src/components/organisms/postcreate/PostCreateBody.js
  client/src/components/pages/LogInPage.js
  client/src/components/pages/PostCreatePage.js
  client/src/components/pages/PostEditPage.js
  client/src/components/pages/SignupPage.js
  client/src/functions/getUserActivityUrl.js
  client/src/functions/scanImage.js
  client/src/hooks/useGetUser.js
Labels: feature, front

#251 [Be/member] Member 리팩토링
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
Labels: bug, back

#236 [FE] SeriesCreate 페이지 API 연결
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Box.js
  client/src/components/atoms/TextArea.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/organisms/Dropdown.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/pages/SeriesCreatePage.js
  client/src/components/pages/ShowcaseCreatePage.js
  client/src/components/pages/ShowcasePage.js
  client/src/constants/Messages.js
  client/src/constants/config.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useInputImage.js
  client/src/store/contentCreateStore.js
  client/src/store/showcaseStore.js
Labels: feature, front

#248 [FE] Post 페이지 뷰어 수정
  client/src/components/molecules/posts/PostContentViewer.js
  client/src/components/molecules/posts/PostIndexLIstRender.js
Labels: feature, front

#255 [FE] SeriesCreate 버그수정
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/Showcasebox.js
  client/src/components/pages/SeriesCreatePage.js
  client/src/constants/Messages.js
  client/src/hooks/useCommentAPI.js
  client/src/store/contentCreateStore.js
  client/src/store/showcaseStore.js
Labels: feature, front

#258 [FE] Showcase 댓글작성시 업데이트로직 추가
  client/src/store/contentCreateStore.js
  client/src/store/showcaseStore.js
Labels: feature, front

#250 [FE] Comment Pagination, Post Category Button 연결
  client/package-lock.json
  client/src/App.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/dropdown/DropdownSeriesList.js
  client/src/components/molecules/list/SeriesCard.js
  client/src/components/molecules/posts/PostTitle.js
  client/src/components/molecules/series/SeriesInfo.js
  client/src/components/molecules/series/SeriesPostList.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/pages/PostListPage.js
  client/src/components/pages/PostPage.js
  client/src/components/pages/SearchPage.js
  client/src/components/pages/SeriesListPage.js
  client/src/components/pages/SeriesPage.js
  client/src/functions/getPostList.js
  client/src/functions/getSeriesList.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useGetPostList.js
  client/src/hooks/useGetSeriesList.js
  client/src/hooks/useGetSeriesListbyUser.js
  client/src/store/seriesStore.js
Labels: feature, front

#254 [FE] Post 페이지 이미지 업로드 로직 구현
  client/src/functions/getSignedUrl.js
  client/src/functions/uploadImage.js
Labels: feature, front

#259 [FE] Category prop 수정
  client/src/components/molecules/ImageCard.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/organisms/showcase/Showcasebox.js
  client/src/constants/Categories.js
Labels: bug, feature, front

#260 [FE] User Edit Page 수정 및 기타 버그 픽스
  client/src/App.js
  client/src/components/atoms/TextEditor.js
  client/src/components/organisms/user/UserActivitiesBox.js
  client/src/components/pages/PostCreatePage.js
  client/src/components/pages/UserEditPage.js
  client/src/functions/getUserActivityUrl.js
  client/src/functions/postUploadImage.js
  client/src/functions/scanImage.js
  client/src/functions/uploadNewUserInfo.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetUserActivity.js
Labels: feature, front

#263 [BE/Deploy] 변경사항 반영
  .github/workflows/client.yml
  client/package-lock.json
  client/src/App.js
  client/src/components/atoms/TextEditor.js
  client/src/components/molecules/ImageCard.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/molecules/dropdown/DropdownSeriesList.js
  client/src/components/molecules/list/SeriesCard.js
  client/src/components/molecules/posts/PostContentViewer.js
  client/src/components/molecules/posts/PostIndexLIstRender.js
  client/src/components/molecules/posts/PostTitle.js
  client/src/components/molecules/series/SeriesInfo.js
  client/src/components/molecules/series/SeriesPostList.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/organisms/showcase/Showcasebox.js
  client/src/components/organisms/user/UserActivitiesBox.js
  client/src/components/pages/PostCreatePage.js
  client/src/components/pages/PostListPage.js
  client/src/components/pages/PostPage.js
  client/src/components/pages/SearchPage.js
  client/src/components/pages/SeriesCreatePage.js
  client/src/components/pages/SeriesListPage.js
  client/src/components/pages/SeriesPage.js
  client/src/components/pages/UserEditPage.js
  client/src/constants/Categories.js
  client/src/constants/Messages.js
  client/src/functions/getPostList.js
  client/src/functions/getSeriesList.js
  client/src/functions/getSignedUrl.js
  client/src/functions/getUserActivityUrl.js
  client/src/functions/postUploadImage.js
  client/src/functions/scanImage.js
  client/src/functions/uploadImage.js
  client/src/functions/uploadNewUserInfo.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetPostList.js
  client/src/hooks/useGetSeriesList.js
  client/src/hooks/useGetSeriesListbyUser.js
  client/src/hooks/useGetUserActivity.js
  client/src/store/contentCreateStore.js
  client/src/store/seriesStore.js
  client/src/store/showcaseStore.js
  server/src/main/java/com/codestates/hobby/domain/common/Writing.java
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
  server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
  server/src/main/resources/logback-spring.xml
Labels: back

#264 [FE] 핫픽스
  client/src/components/molecules/UserInfo.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/organisms/listContainter/PostListContainer.js
  client/src/components/organisms/posts/PostHeaderLayer.js
  client/src/components/pages/PostCreatePage.js
  client/src/components/pages/PostEditPage.js
  client/src/components/pages/PostListPage.js
  client/src/components/pages/PostPage.js
  client/src/components/pages/UserEditPage.js
  client/src/components/pages/UserPage.js
  client/src/constants/Messages.js
  client/src/functions/uploadNewUserInfo.js
  client/src/hooks/useGetUser.js
  client/src/hooks/useGetUserActivity.js
Labels: bug, front

#265 [FE] 핫픽스
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/organisms/Dropdown.js
  client/src/components/organisms/Footer.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Sidebar.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/pages/SeriesCreatePage.js
  client/src/components/pages/ShowcaseCreatePage.js
  client/src/components/pages/ShowcasePage.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useInputImage.js
  client/src/store/contentCreateStore.js
  client/src/store/showcaseStore.js
Labels: bug, feature, front

#268 [BE/Showcase] Comment Count Query 수정
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseCommentRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java
Labels: bug, back

#261 [BE/Cert] authorizeHttpRequests 수정
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
Labels: bug, back

#272 hotfix - #seriesList
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/series/SeriesPostList.js
Labels: feature, front

#277 [FE] HOTFIX
  client/src/components/molecules/posts/PostTitle.js
  client/src/components/pages/PostEditPage.js
Labels: bug, front
