Repository codestates-seb/seb41_main_009, pull requests merged in 2023-01, with the labels that each got.

#8 [#5] feat: 엔티티 생성 및 연관관계 매핑
  .gitignore
  server/build.gradle
  server/src/main/java/com/codestates/hobby/ServerApplication.java
  server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java
  server/src/main/java/com/codestates/hobby/domain/certification/entity/Certification.java
  server/src/main/java/com/codestates/hobby/domain/common/BaseEntity.java
  server/src/main/java/com/codestates/hobby/domain/common/Comment.java
  server/src/main/java/com/codestates/hobby/domain/common/ResourceType.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/notifcation/entity/Notification.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/PostComment.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/ShowcaseComment.java
  server/src/main/java/com/codestates/hobby/domain/subscribe/entity/Subscribe.java
  server/src/main/resources/application.properties
  server/src/main/resources/application.yml
Labels: feature, back

#9 [BE/Category] Controller 1차 구현
  .gitignore
  server/src/main/java/com/codestates/hobby/domain/category/controller/CategoryController.java
  server/src/main/java/com/codestates/hobby/domain/notifcation/controller/NotificationController.java
Labels: feature, back

#12 [BE/Series] Controller 1차 구현
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
Labels: feature, back

#11 [BE/Sub] Controller 1차 구현
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/subscription/controller/SubscriptionController.java
  server/src/main/java/com/codestates/hobby/domain/subscription/entity/Subscription.java
Labels: feature, back

#21 [BE/Post] Controller 1차 구현
  server/build.gradle
  server/src/main/java/com/codestates/hobby/ServerApplication.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/resources/application.yml
Labels: feature, back

#20 [FE/Signin] 페이지 레이아웃 구성
  client/.eslintrc.js
  client/src/App.js
  client/src/components/atom/test.js
  client/src/components/molecule/test.js
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/Navigator.js
  client/src/components/organisms/Sidebar.js
  client/src/components/organisms/SocialLogin.js
  client/src/components/style/test.css
  client/src/components/templates/Signin.js
  client/src/components/test.js
  client/src/pages/style/test.css
  client/src/pages/test.js
  client/src/static/test.js
  client/src/store/test.js
Labels: feature, front

#30 [BE/Category] DTO 구현
  server/src/main/java/com/codestates/hobby/domain/category/dto/CategoryDto.java
Labels: feature, back

#31 [BE/Noti] DTO 및 Controller 리펙토링
  server/src/main/java/com/codestates/hobby/domain/notifcation/controller/NotificationController.java
  server/src/main/java/com/codestates/hobby/domain/notifcation/dto/NotificationDto.java
Labels: feature, back

#32 [BE/Sub] DTO 구현
  server/src/main/java/com/codestates/hobby/domain/subscription/dto/SubscriptionDto.java
Labels: feature, back

#29 [BE/Showcase] DTO 구현 및 Controller 리펙토링
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java
Labels: feature, back

#37 [BE/Showcase] Service 1차 및 Controller 2차 구현
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
Labels: feature, back

#39 [BE/Member] DTO 1차 구현 및 Controller 리팩토링
  server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
Labels: feature, back

#41 [FE] Sidebar 컴포넌트 구현
  client/src/App.js
  client/src/components/molecules/SidebarMenu.js
  client/src/components/organisms/Sidebar.js
Labels: feature, front

#48 [BE/Post] DTO 1차 구현 및 Controller 리펙토링
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
Labels: feature, back

#44 [BE] 공통 설정
  server/build.gradle
  server/src/main/java/com/codestates/hobby/global/config/MvcConfig.java
  server/src/main/java/com/codestates/hobby/global/config/support/CustomPageRequest.java
  server/src/main/java/com/codestates/hobby/global/config/support/PagingArgumentResolver.java
  server/src/main/java/com/codestates/hobby/global/dto/MultiResponseDto.java
  server/src/main/java/com/codestates/hobby/global/dto/PageInfo.java
Labels: feature, back

#45 [FE/Showcase] 레이아웃 구현
  client/.eslintrc.js
  client/src/App.js
  client/src/components/organisms/Showcase/ShowcaseModal.js
  client/src/components/organisms/Showcase/Showcasebox.js
  client/src/components/templates/Showcase.js
Labels: feature, front

#56 [FE] Button 컴포넌트 구현
  client/src/App.js
  client/src/GlobalStyle.js
  client/src/components/atoms/Buttons.js
Labels: feature, front

#53 [BE/Psot] Service 1차 및 Controller 2차 구현
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
Labels: feature, back

#54 [BE/Member] Service 1차, Controller 2차, Mapper 구현 및 Dto 리팩토링
  server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
Labels: feature, back

#59 [Category] Service 1차, Controller 2차, Mapper 구현
  server/src/main/java/com/codestates/hobby/domain/category/controller/CategoryController.java
  server/src/main/java/com/codestates/hobby/domain/category/dto/CategoryDto.java
  server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java
  server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java
  server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
  server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/category/service/CategoryServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/stub/CategoryStub.java
Labels: feature, back

#64 [BE/Series] Service 1차, Controller 2차, Mapper 구현 및 Dto 리팩토링
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
Labels: feature, back

#65 [BE] showcase, comment Mapper 및 테스트 케이스 작성
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/main/resources/application.yml
  server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseServiceTest.java
  server/src/test/java/com/codestates/hobby/utils/ControllerTest.java
Labels: feature, back

#67 [BE] Notification Service 1차 구현
  server/src/main/java/com/codestates/hobby/domain/notifcation/controller/NotificationController.java
  server/src/main/java/com/codestates/hobby/domain/notifcation/service/NotificationService.java
Labels: feature, back

#68 [BE] Subscription Service 1차 구현
  server/src/main/java/com/codestates/hobby/domain/subscription/controller/SubscriptionController.java
  server/src/main/java/com/codestates/hobby/domain/subscription/service/SubscriptionService.java
Labels: feature, back

#57 [FE] Post Page 레이아웃 구현
  client/src/App.js
  client/src/components/molecules/PostHeader.js
  client/src/components/molecules/PostUserInfo.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentHeader.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/organisms/posts/PostCommentContainer.js
  client/src/components/organisms/posts/PostContent.js
  client/src/components/organisms/posts/PostHeaderContainer.js
  client/src/components/organisms/posts/PostSubHeaderContainer.js
  client/src/components/templates/PostPage.js
Labels: feature, front

#71 [BE] FileInfo service 구현
  server/build.gradle
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/ImageType.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java
  server/src/main/java/com/codestates/hobby/global/config/GCSConfig.java
Labels: feature, back

#62 [FE] Input Card 컴포넌트 구현
  client/src/components/molecules/InputCard.js
Labels: feature, front

#69 [FE] User, UserEdit 페이지 레이아웃 구현
  client/src/App.js
  client/src/GlobalStyle.js
  client/src/components/organisms/Navigator.js
  client/src/components/organisms/Sidebar.js
  client/src/components/organisms/user/UserContentBox.js
  client/src/components/organisms/user/UserTitle.js
  client/src/components/templates/Showcase.js
  client/src/components/templates/User.js
  client/src/components/templates/UserEdit.js
  client/src/routes/PublicRoute.js
Labels: feature, front

#78 [BE/Member] 테스트 케이스 작성
  server/src/test/java/com/codestates/hobby/domain/member/MemberControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/member/MemberServiceTest.java
Labels: test, back

#80 [BE/FileInfo] Entity 및 Service 리펙토링
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/SignedURL.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/repository/FileInfoRepository.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java
  server/src/main/resources/application.yml
Labels: back

#79 [BE/Series] 테스트 케이스 작성
  server/src/test/java/com/codestates/hobby/domain/series/SeriesControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/series/SeriesServiceTest.java
Labels: test, back

#86 [BE/Category] Repository 및 Service 계층 구현
  server/src/main/java/com/codestates/hobby/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java
  server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/category/service/CategoryServiceTest.java
Labels: feature, test, back

#85 [FE/Search] 페이지 레이아웃 구현
  client/src/App.js
  client/src/components/organisms/search/SearchResultTitle.js
  client/src/components/templates/Search.js
Labels: feature, front

#77 [FE/component] Feature/stickerlabel 컴포넌트 구현
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/image/logo.svg
  client/src/GlobalStyle.js
  client/src/components/atoms/StickerLabel.js
  client/src/components/atoms/icons.js
  client/src/components/molecules/StickerLabel.js
Labels: feature, front

#76 [FE] Post 생성 페이지 레이아웃 구현
  client/src/App.js
  client/src/components/organisms/Sidebar.js
  client/src/components/organisms/postcreate/PostCreateBody.js
  client/src/components/organisms/postcreate/PostCreateButtons.js
  client/src/components/organisms/postcreate/PostCreateDescription.js
  client/src/components/organisms/postcreate/PostCreateHeader.js
  client/src/components/organisms/postcreate/PostCreateIndex.js
  client/src/components/templates/PostCreatePage.js
Labels: feature, front

#81 [BE/Post] Mapper 및 테스트 케이스 작성
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommendControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommentControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostQueryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/service/PostCommentTest.java
  server/src/test/java/com/codestates/hobby/domain/post/service/PostServiceTest.java
Labels: feature, back

#97 [BE/Category] 카테고리 리펙토링
  server/src/main/java/com/codestates/hobby/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
  server/src/test/java/com/codestates/hobby/domain/category/service/CategoryServiceTest.java
Labels: back

#98 [BE/FileInfo] Controller 구현 및 리펙토링
  server/src/main/java/com/codestates/hobby/domain/fileInfo/controller/FileInfoController.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/BasePath.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/FileInfoDto.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/ImageType.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/SignedURL.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/support/BasePathConverter.java
  server/src/main/java/com/codestates/hobby/global/config/MvcConfig.java
Labels: feature, back

#100 [FE] Font Style Component 구현
  client/src/App.js
  client/src/components/atoms/AcrylicBase.js
  client/src/components/atoms/FontStyle.js
Labels: feature, front

#70 [FE] Page Header 컴포넌트 구현
  client/src/components/atoms/Buttons.js
  client/src/components/organisms/PageHeader.js
  client/src/components/organisms/listcontents/ListHeader.js
  client/src/components/templates/PostList.js
  client/src/components/templates/SeriesList.js
Labels: feature, front

#104 [FE] Font 컴포넌트 리팩토링
  client/public/index.html
  client/src/App.js
  client/src/GlobalStyle.js
  client/src/components/atoms/FontStyle.js
  client/src/styles/typo.js
Labels: feature, front

#107 [BE/File] 리펙토링
  server/build.gradle
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/repository/FileInfoRepository.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/main/resources/application.yml
Labels: back

#105 [FE] Pagination 컴포넌트 구현 #95
  client/src/components/atoms/StickerLabel.js
  client/src/components/molecules/Dialog.js
  client/src/components/molecules/Pagination.js
  client/src/components/molecules/stickerLabel/SplashStickerLabel.js
  client/src/components/molecules/stickerLabel/StickerLabel.js
  client/src/components/molecules/stickerLabel/TiltedContainer.js
  client/src/components/templates/Test.js
Labels: feature, front

#96 [FE] Comments 컴포넌트 구현
  client/src/components/atoms/Input.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentHeader.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/organisms/Comments.js
  client/src/components/organisms/posts/PostCommentContainer.js
  client/src/components/templates/PostPage.js
Labels: feature, front

#109 [FE] Sidebar 컴포넌트 구현
  client/src/App.js
  client/src/components/atoms/Buttons.js
  client/src/components/molecules/SidebarMenu.js
  client/src/components/molecules/SidebarTagsContainer.js
  client/src/components/organisms/Sidebar.js
  client/src/components/templates/PostList.js
  client/src/components/templates/PostPage.js
  client/src/components/templates/Search.js
  client/src/components/templates/SeriesList.js
  client/src/constants/Categories.js
  client/src/styles/Selected.js
Labels: feature, front

#111 [FE] Header 컴포넌트 구현
  client/src/App.js
  client/src/components/molecules/SearchInput.js
  client/src/components/organisms/Navigator.js
Labels: feature, front

#113 [BE/Showcase] JoinTable 매핑 방법 변경
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/ShowcaseImage.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseImageRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseServiceTest.java
  server/src/test/java/com/codestates/hobby/utils/DatabaseCleanup.java
Labels: feature, test, back

#110 [FE/Showcase] 공용 컴포넌트 구현
  client/src/components/atoms/Box.js
  client/src/components/atoms/Category.js
  client/src/components/atoms/Input.js
  client/src/components/atoms/Nickname.js
  client/src/components/atoms/UserImage.js
  client/src/components/molecules/ImageCard.js
  client/src/components/molecules/UserInfo.js
  client/src/components/organisms/Showcase/Showcasebox.js
  client/src/components/templates/Showcase.js
Labels: feature, front

#112 [FE] Series Page 레이아웃 구현
  client/src/App.js
  client/src/components/molecules/SeriesInfoContainer.js
  client/src/components/molecules/SeriesPostListContainer.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/templates/SeriesPage.js
Labels: feature, front

#130 [Be/Member] Data access 계층 구현, Service 2차 구현
  server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/hobby/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
Labels: feature, back

#133 [BE/Showcase] Test 구현 및 리펙토링
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/stub/ShowcaseStub.java
  server/src/test/java/com/codestates/hobby/utils/ControllerTest.java
Labels: test, back

#132 [FE] 회원가입 페이지 구현
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/Signupbox.js
  client/src/components/templates/Signup.js
  client/src/constants/Messages.js
Labels: feature, front

#134 [FE] LNB, Series/PostHeader 컴포넌트 구현
  client/.eslintrc.js
  client/src/components/atoms/Buttons.js
  client/src/components/atoms/Category.js
  client/src/components/atoms/Nickname.js
  client/src/components/molecules/PostHeader.js
  client/src/components/molecules/PostTitle.js
  client/src/components/molecules/PostUserInfo.js
  client/src/components/molecules/SeriesTitle.js
  client/src/components/molecules/UserInfo.js
  client/src/components/organisms/Lnb.js
  client/src/components/organisms/posts/PostHeader.js
  client/src/components/organisms/posts/PostHeaderContainer.js
  client/src/components/organisms/series/SeriesHeader.js
  client/src/components/templates/PostPage.js
  client/src/index.js
Labels: feature, front

#138 [FE] 404 에러 페이지 구현
  client/src/App.js
  client/src/components/templates/404ErrorPage.js
Labels: feature, front

#135 [Be/Series] Data access 계층 구현, Service 2차 구현
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
  server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
Labels: feature, back

#137 [FE] List 컴포넌트 구현#92
  client/src/GlobalStyle.js
  client/src/components/atoms/AcrylicBase.js
  client/src/components/atoms/Buttons.js
  client/src/components/molecules/Dialog.js
  client/src/components/molecules/Pagination.js
  client/src/components/molecules/UserInfo.js
  client/src/components/molecules/list/PostList.js
  client/src/components/molecules/list/SeriesList.js
  client/src/components/molecules/list/SeriesPostList.js
  client/src/components/molecules/stickerLabel/SplashStickerLabel.js
  client/src/components/molecules/stickerLabel/StickerLabel.js
  client/src/components/organisms/Showcase/Showcasebox.js
  client/src/components/organisms/listcontents/PostListContainer.js
  client/src/components/organisms/posts/PostHeader.js
  client/src/components/templates/PostList.js
  client/src/components/templates/Test.js
  client/src/constants/Paragraph.js
  client/src/static/githubLogo.svg
  client/src/static/googleLogo.svg
  client/src/static/validIcons.svg
  client/src/static/validfalseIcons.svg
  client/src/styles/typo.js
Labels: feature, front

#139 [BE/File] 연관관계 매핑 방법에 대한 변경
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/MockFileInfoService.java
  server/src/test/java/com/codestates/hobby/domain/fileInfo/service/FileInfoServiceTest.java
Labels: test, back

#136 [Be/Post] Data access 계층 구현, Service 2차 구현, Test 구현
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostCommentRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommendControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommentControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostQueryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/service/PostServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentServiceTest.java
Labels: feature, back

#141 [BE/Post] Entity, Service 리펙토링 및 유효성 검증 구현
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/repository/PostCommentRepository.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommentControllerTest.java
Labels: feature, back

#142 [Be/Member] 유효성 검증 구현 및 리펙토링
  server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
Labels: feature, back

#145 [BE/Series] 유효성 검증 구현 및 리펙토링
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
  server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
Labels: feature, back

#143 [BE/Cat] 하이버네이트 L2 Cache 적용 및 테스트
  server/build.gradle
  server/src/main/java/com/codestates/hobby/domain/category/controller/CategoryController.java
  server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java
  server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java
  server/src/main/java/com/codestates/hobby/domain/category/repository/CategoryRepository.java
  server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
  server/src/main/java/com/codestates/hobby/global/config/CachingConfig.java
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
  server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryIntegrationTest.java
  server/src/test/java/com/codestates/hobby/domain/category/repository/CategoryRepositoryTest.java
  server/src/test/java/com/codestates/hobby/domain/category/service/CategoryServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/stub/CategoryStub.java
  server/src/test/java/com/codestates/hobby/utils/ControllerTest.java
Labels: feature, test, back

#146 [BE/Post] Controller, Dto, Mapper 리펙토링
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
Labels: feature, back

#147 [FE] Series List Page 구현
  client/src/App.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/list/SeriesCard.js
  client/src/components/molecules/series/SeriesPostList.js
  client/src/components/organisms/listContainter/PostListContainer.js
  client/src/components/organisms/listContainter/SeriesListContainer.js
  client/src/components/pages/SeriesListPage.js
  client/src/constants/URL.js
  client/src/constants/dummyData.js
  client/src/hooks/test.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetSeriesList.js
Labels: feature, front

#151 [BE] Service 계층 3차 구현
  server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/main/java/com/codestates/hobby/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/hobby/global/exception/BusinessLogicException.java
  server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/hobby/global/response/ErrorResponse.java
  server/src/test/java/com/codestates/hobby/domain/post/service/PostServiceTest.java
Labels: feature, back

#152 [BE/FileInfo] FileInfo 오류 수정
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileURL.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/mapper/FileInfoMapper.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/repository/FileInfoRepository.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/test/java/com/codestates/hobby/domain/fileInfo/service/FileInfoServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/stub/FileInfoStub.java
Labels: bug, back

#153 [BE/Showcase] Showcase 리펙토링 및 오류 수정
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/test/java/com/codestates/hobby/domain/showcase/ShowcaseCommentControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/ShowcaseControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/ShowcaseIntegrationTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/service/ShowcaseServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/stub/ShowcaseStub.java
Labels: bug, back

#154 [BE] Exception 수정
  server/src/main/java/com/codestates/hobby/domain/category/mapper/CategoryMapper.java
  server/src/main/java/com/codestates/hobby/domain/category/service/CategoryService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/controller/FileInfoController.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostService.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseCommentService.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/main/java/com/codestates/hobby/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/hobby/global/response/ErrorResponse.java
  server/src/test/java/com/codestates/hobby/domain/fileInfo/service/FileInfoServiceTest.java
Labels: feature, back

#156 [BE/Member] 로그인 구현 및 Member 리팩토링
  server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionConst.java
  server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionManager.java
  server/src/main/java/com/codestates/hobby/domain/auth/controller/LoginController.java
  server/src/main/java/com/codestates/hobby/domain/auth/dto/LoginDto.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/LoginService.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/MemberDetailsService.java
  server/src/main/java/com/codestates/hobby/domain/auth/utils/CustomAuthorityUtils.java
  server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
  server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
  server/src/main/resources/application.yml
Labels: feature, back

#157 [FE] User Page 구현
  client/src/App.js
  client/src/components/atoms/CardContainer.js
  client/src/components/molecules/UserInfo.js
  client/src/components/molecules/stickerLabel/SplashStickerLabel.js
  client/src/components/molecules/stickerLabel/StickerLabel.js
  client/src/components/organisms/user/UserActivitiesBox.js
  client/src/components/organisms/user/UserContentBox.js
  client/src/components/organisms/user/UserTitle.js
  client/src/components/pages/UserPage.js
  client/src/constants/UserPageDataLists.js
  client/src/constants/dummyData.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetSeriesList.js
  client/src/hooks/useGetUser.js
  client/src/hooks/useGetUserActivity.js
Labels: feature, front

#159 [FE] Post Page, Series Page 구현 , Header 컴포넌트 변경
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/molecules/SearchInput.js
  client/src/components/molecules/UserInfo.js
  client/src/components/molecules/posts/PostContentViewer.js
  client/src/components/molecules/posts/PostIndexLIstRender.js
  client/src/components/molecules/posts/PostTitle.js
  client/src/components/molecules/series/SeriesInfo.js
  client/src/components/molecules/series/SeriesPostList.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/organisms/Showcase/Showcasebox.js
  client/src/components/organisms/listContainter/PostListContainer.js
  client/src/components/organisms/posts/PostContent.js
  client/src/components/organisms/posts/PostContentLayer.js
  client/src/components/organisms/posts/PostHeaderLayer.js
  client/src/components/organisms/posts/PostSubHeaderContainer.js
  client/src/components/organisms/posts/PostSubHeaderLayer.js
  client/src/components/pages/PostListPage.js
  client/src/components/pages/PostPage.js
  client/src/components/pages/SeriesListPage.js
  client/src/components/pages/SeriesPage.js
  client/src/constants/Paragraph.js
  client/src/constants/dummyData.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetPostList.js
  client/src/styles/typo.js
Labels: feature, front

#172 [BE/Test] 테스트 유틸 클래스 분리
  server/src/test/java/com/codestates/hobby/domain/category/controller/CategoryControllerTest.java
  server/src/test/java/com/codestates/hobby/utils/ControllerTest.java
  server/src/test/java/com/codestates/hobby/utils/IntegrationTest.java
  server/src/test/java/com/codestates/hobby/utils/TestUtils.java
Labels: test, back

#171 [BE/Showcase] 무한 스크롤 구현
  server/src/main/java/com/codestates/hobby/domain/fileInfo/mapper/FileInfoMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/main/java/com/codestates/hobby/global/config/MvcConfig.java
  server/src/main/java/com/codestates/hobby/global/config/support/InfiniteScrollArgumentResolver.java
  server/src/main/java/com/codestates/hobby/global/config/support/InfiniteScrollRequest.java
  server/src/test/java/com/codestates/hobby/domain/showcase/ShowcaseControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/stub/ShowcaseStub.java
Labels: feature, back

#173 [BE/Member] Member 리팩토링
  server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionManager.java
  server/src/main/java/com/codestates/hobby/domain/auth/controller/HomeController.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/MemberDetailsService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/member/controller/MemberController.java
  server/src/main/java/com/codestates/hobby/domain/member/dto/MemberDto.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/mapper/MemberMapper.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
Labels: feature, back

#174 [BE/Post] Post 리팩토링
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommendController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostCommentController.java
  server/src/main/java/com/codestates/hobby/domain/post/controller/PostQueryController.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostMapper.java
  server/src/main/java/com/codestates/hobby/domain/post/service/PostCommentService.java
Labels: bug, back

#175 [BE/Series] Series 리팩토링
  server/src/main/java/com/codestates/hobby/domain/series/controller/SeriesController.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
  server/src/main/java/com/codestates/hobby/domain/series/repository/SeriesRepository.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
Labels: feature, back

#160 [FE] Showcase/ShowcaseModal 페이지 1차 구현
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Box.js
  client/src/components/atoms/Category.js
  client/src/components/molecules/ImageCard.js
  client/src/components/molecules/ShowcaseTitle.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentHeader.js
  client/src/components/organisms/Comments.js
  client/src/components/organisms/Showcase/ShowcaseModal.js
  client/src/components/organisms/Showcase/Showcasebox.js
  client/src/components/pages/ShowcasePage.js
  client/src/hooks/useIntersect.js
  client/src/store/showcaseModalStore.js
  client/src/store/showcaseStore.js
  client/src/tests/showcaseDummy.js
Labels: feature, front

#180 [BE/Mail] 이메일 전송 기능 구현
  server/.gitignore
  server/build.gradle
  server/src/main/java/com/codestates/hobby/ServerApplication.java
  server/src/main/java/com/codestates/hobby/domain/auth/entity/Certification.java
  server/src/main/java/com/codestates/hobby/domain/auth/event/CertificationCreatedEvent.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/CertificationEventHandler.java
  server/src/main/java/com/codestates/hobby/global/config/GCSConfig.java
  server/src/main/java/com/codestates/hobby/global/support/mail/EmailService.java
  server/src/main/java/com/codestates/hobby/global/support/mail/GoogleEmailService.java
  server/src/main/java/com/codestates/hobby/global/support/mail/MockEmailService.java
  server/src/main/resources/application.yml
  server/src/main/resources/templates/email-certification-template.html
Labels: feature, back

#182 [Be/Showcase] 댓글 반환하는 방식 변경
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommentController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseQueryController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseCommentRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/main/java/com/codestates/hobby/global/config/support/InfiniteScrollArgumentResolver.java
  server/src/main/java/com/codestates/hobby/global/dto/DefaultPageInfo.java
  server/src/main/java/com/codestates/hobby/global/dto/InfinitePageInfo.java
  server/src/main/java/com/codestates/hobby/global/dto/MultiResponseDto.java
  server/src/main/java/com/codestates/hobby/global/dto/PageInfo.java
  server/src/test/java/com/codestates/hobby/domain/stub/ShowcaseCommentStub.java
Labels: bug, back

#183 [Be/Post, Series] post, series 엔티티 및 DB 구성 방식 변경
  server/src/main/java/com/codestates/hobby/domain/auth/controller/HomeController.java
  server/src/main/java/com/codestates/hobby/domain/common/Writing.java
  server/src/main/java/com/codestates/hobby/domain/post/dto/PostCommentDto.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/post/mapper/PostCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostCommentControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/controller/PostControllerTest.java
  server/src/test/java/com/codestates/hobby/domain/post/service/PostServiceTest.java
  server/src/test/java/com/codestates/hobby/domain/post/tempTest/AsyncTest.java
Labels: feature, back

#184 [BE/Deploy] 배포를 위한 Profile 재설정
  server/build.gradle
  server/src/main/java/com/codestates/hobby/ServerApplication.java
  server/src/main/java/com/codestates/hobby/domain/common/BaseEntity.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/entity/FileInfo.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/mapper/FileInfoMapper.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/GCSFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/MockFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/S3FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/notifcation/entity/Notification.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
  server/src/main/java/com/codestates/hobby/domain/subscription/entity/Subscription.java
  server/src/main/java/com/codestates/hobby/global/config/GCSConfig.java
  server/src/main/java/com/codestates/hobby/global/dto/ErrorResponse.java
  server/src/main/java/com/codestates/hobby/global/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/hobby/global/support/mail/GoogleEmailService.java
  server/src/main/java/com/codestates/hobby/global/support/mail/MockEmailService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-prod.yml
  server/src/main/resources/application.yml
  server/src/main/resources/data.sql
Labels: feature, back

#179 [FE] User Edit Page 구현
  client/src/api/ImageInstance.js
  client/src/components/atoms/UserImage.js
  client/src/components/molecules/InputCard.js
  client/src/components/pages/UserEditPage.js
  client/src/constants/Messages.js
  client/src/constants/Regexp.js
  client/src/functions/isValid.js
Labels: feature, front

#177 [FE] Login 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/molecules/UserInfo.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/Signupbox.js
  client/src/constants/Messages.js
  client/src/routes/PrivateRoute.js
  client/src/routes/ProtectedRoute.js
  client/src/store/useAuthStore.js
Labels: feature, front

#178 [FE] Text Editor 구현
  client/package-lock.json
  client/package.json
  client/src/components/atoms/Buttons.js
  client/src/components/atoms/TextEditor.js
  client/src/components/organisms/postcreate/PostCreateBody.js
  client/src/components/organisms/postcreate/PostCreateButtons.js
  client/src/components/organisms/postcreate/PostCreateDescription.js
  client/src/components/organisms/postcreate/PostCreateHeader.js
  client/src/components/pages/PostCreatePage.js
  client/src/constants/Messages.js
  client/src/functions/uploadImage.js
Labels: feature, front

#181 [BE/Auth] Auth 리팩토링
  server/src/main/java/com/codestates/hobby/domain/auth/controller/HomeController.java
  server/src/main/java/com/codestates/hobby/domain/auth/controller/LoginController.java
  server/src/main/java/com/codestates/hobby/domain/auth/dto/LoginDto.java
  server/src/main/java/com/codestates/hobby/domain/auth/filter/JsonAuthenticationFilter.java
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginFailureHandler.java
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginSuccessHandler.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/LoginService.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
Labels: feature, back

#186 [BE/Debug] 앱 실행시 발생하는 오류 수정
  server/src/main/java/com/codestates/hobby/domain/auth/Session/SessionConst.java
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginFailureHandler.java
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginSuccessHandler.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/MockFileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
Labels: bug, back

#189 [BE/Showcase] 쇼케이스 및 댓글 조회 리펙토링
  server/src/main/java/com/codestates/hobby/domain/fileInfo/dto/ImageProjection.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/repository/FileInfoRepository.java
  server/src/main/java/com/codestates/hobby/domain/fileInfo/service/FileInfoService.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/CommentProjection.java
  server/src/main/java/com/codestates/hobby/domain/showcase/dto/ShowcaseDto.java
  server/src/main/java/com/codestates/hobby/domain/showcase/entity/Showcase.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseCommentMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/mapper/ShowcaseMapper.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseCommentRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/repository/ShowcaseRepository.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
  server/src/test/java/com/codestates/hobby/domain/fileInfo/service/FileInfoServiceTest.java
Labels: bug, back

#185 [FE] OAuth 컨테이너 제거
  client/src/components/pages/LogInPage.js
  client/src/components/pages/SignupPage.js
Labels: front

#194 [FE] Git에서 반영되지 않은 파일명 변경 사항 수정
  client/src/components/atoms/Icons.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/organisms/showcase/Showcasebox.js
Labels: bug, front

#199 [BE/Cert] 이메일 인증 기능 구현
  server/src/main/java/com/codestates/hobby/ServerApplication.java
  server/src/main/java/com/codestates/hobby/domain/auth/controller/LoginController.java
  server/src/main/java/com/codestates/hobby/domain/auth/dto/CertificationCreatedEvent.java
  server/src/main/java/com/codestates/hobby/domain/auth/dto/CertificationPatchRequest.java
  server/src/main/java/com/codestates/hobby/domain/auth/entity/Certification.java
  server/src/main/java/com/codestates/hobby/domain/auth/repository/CertificationRepository.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/CertificationEventHandler.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/CertificationService.java
  server/src/main/java/com/codestates/hobby/domain/member/repository/MemberRepository.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/global/dto/ErrorResponse.java
  server/src/main/java/com/codestates/hobby/global/exception/ExceptionCode.java
  server/src/main/java/com/codestates/hobby/global/exception/GlobalExceptionAdvice.java
  server/src/main/java/com/codestates/hobby/global/support/mail/GoogleEmailService.java
  server/src/main/resources/application-prod.yml
Labels: feature, back

#198 [BE/Debug] 로그인 성공/실패 응답 수정, member/series 삭제 기능 수정
  .github/workflows/gradle.yml
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginFailureHandler.java
  server/src/main/java/com/codestates/hobby/domain/auth/handler/CustomLoginSuccessHandler.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/LoginService.java
  server/src/main/java/com/codestates/hobby/domain/auth/service/UserDetailsServiceImpl.java
  server/src/main/java/com/codestates/hobby/domain/auth/session/SessionConst.java
  server/src/main/java/com/codestates/hobby/domain/member/entity/Member.java
  server/src/main/java/com/codestates/hobby/domain/member/service/MemberService.java
  server/src/main/java/com/codestates/hobby/domain/post/entity/Post.java
  server/src/main/java/com/codestates/hobby/domain/series/dto/SeriesDto.java
  server/src/main/java/com/codestates/hobby/domain/series/entity/Series.java
  server/src/main/java/com/codestates/hobby/domain/series/mapper/SeriesMapper.java
  server/src/main/java/com/codestates/hobby/domain/series/service/SeriesService.java
  server/src/main/java/com/codestates/hobby/global/config/SecurityConfig.java
  server/src/test/java/com/codestates/hobby/utils/ControllerTest.java
  server/src/test/java/com/codestates/hobby/utils/IntegrationTest.java
Labels: bug, back

#190 [FE] Sidebar 수정
  client/src/components/molecules/SearchInput.js
  client/src/components/molecules/sidbar/SidebarMenu.js
  client/src/components/molecules/sidbar/SidebarTagsContainer.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/Sidebar.js
  client/src/components/pages/404ErrorPage.js
  client/src/store/sidebarStore.js
Labels: feature, front

#195 [FE] Client 배포 workflow 구현
  .github/workflows/client.yml
Labels: feature, front

#202 [FE] Loading 컴포넌트 구현
  client/src/components/atoms/Loading.js
  client/src/components/pages/SeriesListPage.js
  client/src/components/pages/UserEditPage.js
  client/src/components/pages/UserPage.js
Labels: feature, front

#197 [FE] Search 페이지 수정, Comment 구현
  client/src/App.js
  client/src/components/molecules/SearchInput.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentContentsContainer.js
  client/src/components/molecules/comments/CommentHeader.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/list/SeriesCard.js
  client/src/components/organisms/Comments.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/showcase/ShowcaseModal.js
  client/src/components/pages/PostPage.js
  client/src/components/pages/SearchPage.js
  client/src/components/pages/ShowcasePage.js
  client/src/constants/dummyData.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useGetPost.js
Labels: feature, front

#204 [FE] Series Create 페이지 구현
  client/src/App.js
  client/src/components/atoms/Buttons.js
  client/src/components/atoms/TextArea.js
  client/src/components/molecules/showcase/ShowcaseImageInput.js
  client/src/components/organisms/Dropdown.js
  client/src/components/pages/SeriesCreatePage.js
  client/src/components/pages/ShowcaseCreatePage.js
  client/src/store/showcaseCreateStore.js
Labels: feature, front

#206 [FE] Series List, User Page API 연결
  client/src/App.js
  client/src/components/atoms/Nickname.js
  client/src/components/molecules/list/NoPost.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/list/SeriesCard.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/user/UserActivitiesBox.js
  client/src/components/pages/SeriesListPage.js
  client/src/functions/getUserActivityUrl.js
  client/src/hooks/useGetPost.js
  client/src/hooks/useGetSeriesList.js
  client/src/hooks/useGetUser.js
  client/src/hooks/useGetUserActivity.js
Labels: feature, front

#212 [FE] Showcase 페이지 2차 구현 및 API 연결
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/molecules/showcase/ShowcaseImageInput.js
  client/src/components/organisms/showcase/Showcasebox.js
  client/src/components/pages/ShowcasePage.js
  client/src/hooks/useInputImage.js
  client/src/hooks/useIntersect.js
  client/src/store/showcaseCreateStore.js
  client/src/store/showcaseStore.js
  client/src/tests/showcaseDummy.js
Labels: feature, front

#217 [FE] Login Authorization Header 구현
  client/src/App.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Loginbox.js
  client/src/hooks/useGetUser.js
  client/src/store/useAuthStore.js
Labels: feature, front

#209 [FE] SearchPage 수정, LNB 구현, SeriesPage 구현
  client/src/App.js
  client/src/components/atoms/Buttons.js
  client/src/components/molecules/SearchInput.js
  client/src/components/molecules/comments/Comment.js
  client/src/components/molecules/comments/CommentInputContainer.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/series/SeriesInfo.js
  client/src/components/molecules/series/SeriesPostList.js
  client/src/components/organisms/Footer.js
  client/src/components/organisms/Lnb.js
  client/src/components/organisms/SeriesHeader.js
  client/src/components/organisms/comment/Comments.js
  client/src/components/organisms/listContainter/PostListContainer.js
  client/src/components/organisms/listContainter/SeriesListContainer.js
  client/src/components/organisms/posts/PostHeaderLayer.js
  client/src/components/pages/PostInSeriesPage.js
  client/src/components/pages/PostListPage.js
  client/src/components/pages/SearchPage.js
  client/src/components/pages/SeriesListPage.js
  client/src/components/pages/SeriesPage.js
  client/src/constants/dummyData.js
  client/src/hooks/useCommentAPI.js
  client/src/hooks/useGetPost.js
  client/src/store/seriesStore.js
Labels: feature, front

#208 [BE/Showcase] 검색 API 추가
  server/src/main/java/com/codestates/hobby/domain/category/entity/Category.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseCommendController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/controller/ShowcaseController.java
  server/src/main/java/com/codestates/hobby/domain/showcase/service/ShowcaseService.java
  server/src/test/java/com/codestates/hobby/domain/showcase/ShowcaseControllerTest.java
Labels: feature, back

#213 [FE] 회원가입 기능 수정
  client/src/components/atoms/signup/SignupComponents.js
  client/src/components/molecules/signup/EmailBox.js
  client/src/components/molecules/signup/EmailValidationBox.js
  client/src/components/molecules/signup/NicknameBox.js
  client/src/components/molecules/signup/PasswordBox.js
  client/src/components/molecules/signup/PasswordCheckBox.js
  client/src/components/organisms/Loginbox.js
  client/src/components/organisms/Signupbox.js
  client/src/components/organisms/postcreate/PostCreateButtons.js
  client/src/components/pages/UserEditPage.js
  client/src/constants/Messages.js
Labels: feature, front

#214 [FE] Sidebar 수정
  client/src/App.js
  client/src/components/organisms/Header.js
  client/src/components/organisms/Sidebar.js
  client/src/components/pages/PostListPage.js
  client/src/routes/PrivateRoute.js
  client/src/routes/ProtectedRoute.js
  client/src/routes/PublicRoute.js
Labels: feature, front

#222 [FE] Post -> Series 기능 추가, index 구현
  client/package-lock.json
  client/src/App.js
  client/src/components/molecules/dropdown/DropdownSeriesList.js
  client/src/components/molecules/list/PostCard.js
  client/src/components/molecules/posts/PostContentViewer.js
  client/src/components/molecules/posts/PostIndexLIstRender.js
  client/src/components/organisms/Footer.js
  client/src/components/organisms/posts/PostSubHeaderLayer.js
  client/src/constants/dummyData.js
  client/src/hooks/useGetSeriesListbyUser.js
  client/src/store/postStore.js
  client/src/styles/typo.js
Labels: feature, front
